apiVersion: v1
kind: Namespace
metadata:
  name: web-app-project
  labels:
    environment: development
    app: web-app
--
apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-quota
  namespace: web-app-project
spec:
  hard:
    # Compute Limits
    limits.cpu: "2"           # Total CPU limit for all containers: 2 CPU cores
    limits.memory: "4Gi"      # Total memory limit for all containers: 4 GiB
    pods: "10"                # Max number of Pods allowed in the namespace
    
    # Ephemeral Storage Quota (This satisfies the 5GB request)
    # This limits the total combined usage of emptyDir volumes and container writable layers.
    limits.ephemeral-storage: "5Gi" 

----
apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: web-app-project
spec:
  limits:
  - default:
      cpu: 500m               # Default CPU limit per container
      memory: 512Mi           # Default memory limit per container
      ephemeral-storage: 1Gi  # Default ephemeral storage limit per container
    defaultRequest:
      cpu: 100m               # Default CPU request per container
      memory: 128Mi           # Default memory request per container
      ephemeral-storage: 500Mi # Default ephemeral storage request per container
    type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-deployment
  namespace: web-app-project
  labels:
    app: simple-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-webapp
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
      - name: webapp-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-cache         # Mount the temporary volume
          mountPath: /tmp/cache   # Path where the volume will be accessible inside the container
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
            # Explicitly setting ephemeral storage limit to ensure compliance with the ResourceQuota
            ephemeral-storage: 1Gi 
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 500Mi
      volumes:
      - name: app-cache
        # Defines the emptyDir volume. This volume is created when the Pod starts
        # and deleted when the Pod is removed (ephemeral).
        emptyDir: {}
___
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-svc
  namespace: web-app-project
  labels:
    app: simple-webapp
spec:
  selector:
    app: simple-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # ClusterIP exposes the service internally within the cluster
  type: ClusterIP 

--
