apiVersion: v1
kind: Pod
metadata:
  name: nginx-web-pod
  labels:
    app: web
    env: production
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
