apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kmi-helm
  namespace: default

spec:
  project: default

  source:
    repoURL: https://github.com/DevopsSwapnil/kmi-helm.git
    targetRevision: main
    path: helm/kmi-helm   # 👈 THIS is your helm chart location

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true